import { Env, Platform } from '@expo/eas-build-job';
import { Command, Flags } from '@oclif/core';

import { getAuthExpoHeaders, retrieveExpoCredentials } from '../lib/auth';
import {
  RequestedPlatform,
  getPrivateExpoConfigAsync,
  resolveServerUrl,
} from '../lib/expoConfig';
import { fetchWithRetries } from '../lib/fetch';
import Log from '../lib/log';
import { ora } from '../lib/ora';
import { isExpoInstalled } from '../lib/package';
import { resolvePackageRunner } from '../lib/packageRunner';
import { confirmAsync } from '../lib/prompts';
import { resolveRuntimeVersionAsync } from '../lib/runtimeVersion';
import { uploadSourcemapsToSentry } from '../lib/sentry';
import { resolveVcsClient } from '../lib/vcs';
import { resolveWorkflowAsync } from '../lib/workflow';

type UploadSourcemapsPlatform = 'ios' | 'android' | 'both';

interface DashboardUpdateItem {
  updateUUID: string;
  updateId: string;
  platform: string;
  createdAt: string;
}

export default class UploadSourcemaps extends Command {
  static override args = {};
  static override description = 'Upload sourcemaps from the current export output to Sentry';
  static override examples = ['<%= config.bin %> <%= command.id %> --branch production'];
  static override flags = {
    platform: Flags.string({
      type: 'option',
      options: ['ios', 'android', 'both'],
      default: 'both',
      required: false,
      description: 'Target platform: ios, android, or both',
    }),
    channel: Flags.string({
      description: 'Deprecated. Use RELEASE_CHANNEL env var instead.',
      required: false,
      deprecated: {
        message:
          'Channel was initially used to provide RELEASE_CHANNEL in the environment when resolving the runtime version. It is no longer needed, you can use RELEASE_CHANNEL={channel} eoas upload-sourcemaps --branch={branch} instead',
      },
    }),
    branch: Flags.string({
      description: 'Name of the branch to use when resolving updates',
      required: true,
    }),
    nonInteractive: Flags.boolean({
      description: 'Run command in non-interactive mode',
      default: false,
    }),
    outputDir: Flags.string({
      description:
        "Export output directory generated by 'expo export' (must include metadata and sourcemaps)",
      default: 'dist',
    }),
    packageRunner: Flags.string({
      description:
        'Package runner to use for spawning sentry-cli/expo commands (e.g. npx, bunx, pnpx). Can also be set via EOAS_PACKAGE_RUNNER env var. Defaults to npx.',
      required: false,
    }),
  };

  private sanitizeFlags(flags: any): {
    branch: string;
    nonInteractive: boolean;
    outputDir: string;
    packageRunner: string;
    platform: UploadSourcemapsPlatform;
    providedDeprecatedChannel?: string;
  } {
    return {
      branch: flags.branch,
      nonInteractive: flags.nonInteractive,
      outputDir: flags.outputDir,
      packageRunner: resolvePackageRunner(flags.packageRunner, process.cwd()),
      platform: flags.platform,
      providedDeprecatedChannel: flags.channel,
    };
  }

  private resolveRequestedPlatform(platform: UploadSourcemapsPlatform): RequestedPlatform {
    if (platform === 'ios') {
      return RequestedPlatform.Ios;
    }
    if (platform === 'android') {
      return RequestedPlatform.Android;
    }
    return RequestedPlatform.All;
  }

  public async run(): Promise<void> {
    const credentials = retrieveExpoCredentials();
    if (!credentials.token && !credentials.sessionSecret) {
      Log.error('You are not logged to eas, please run `eas login`');
      process.exit(1);
    }

    if (!process.env.SENTRY_AUTH_TOKEN) {
      Log.error('SENTRY_AUTH_TOKEN is required for sourcemap upload');
      process.exit(1);
    }

    const { flags } = await this.parse(UploadSourcemaps);
    const { branch, nonInteractive, outputDir, packageRunner, platform, providedDeprecatedChannel } =
      this.sanitizeFlags(flags);

    if (!branch) {
      Log.error('Branch name is required');
      process.exit(1);
    }

    const projectDir = process.cwd();
    const hasExpo = isExpoInstalled(projectDir);
    if (!hasExpo) {
      Log.error('Expo is not installed in this project. Please install Expo first.');
      process.exit(1);
    }

    const vcsClient = resolveVcsClient(true);
    await vcsClient.ensureRepoExistsAsync();

    const config = await getPrivateExpoConfigAsync(projectDir, {
      env: {
        ...(process.env as Env),
        ...(providedDeprecatedChannel ? { RELEASE_CHANNEL: providedDeprecatedChannel } : {}),
      },
      packageRunner,
    });
    const serverUrl = await resolveServerUrl(config).catch(e => {
      Log.error(e.message);
      process.exit(1);
    });

    if (!nonInteractive) {
      const confirmed = await confirmAsync({
        message: `Is this the correct URL of your self-hosted update server? ${serverUrl}`,
        name: 'export',
        type: 'confirm',
      });
      if (!confirmed) {
        Log.error('Please run `eoas init` to setup the correct update url');
        process.exit(1);
      }
    }

    const requestedPlatform = this.resolveRequestedPlatform(platform);
    const runtimeSpinner = ora('🔄 Resolving runtime version...').start();
    const runtimeVersions = [
      ...(!requestedPlatform ||
      requestedPlatform === RequestedPlatform.All ||
      requestedPlatform === RequestedPlatform.Ios
        ? [
            {
              runtimeVersion: (
                await resolveRuntimeVersionAsync({
                  exp: config,
                  platform: 'ios',
                  workflow: await resolveWorkflowAsync(projectDir, Platform.IOS, vcsClient),
                  projectDir,
                  env: {
                    ...(process.env as Env),
                    ...(providedDeprecatedChannel
                      ? { RELEASE_CHANNEL: providedDeprecatedChannel }
                      : {}),
                  },
                })
              )?.runtimeVersion,
              platform: 'ios',
            },
          ]
        : []),
      ...(!requestedPlatform ||
      requestedPlatform === RequestedPlatform.All ||
      requestedPlatform === RequestedPlatform.Android
        ? [
            {
              runtimeVersion: (
                await resolveRuntimeVersionAsync({
                  exp: config,
                  platform: 'android',
                  workflow: await resolveWorkflowAsync(projectDir, Platform.ANDROID, vcsClient),
                  projectDir,
                  env: {
                    ...(process.env as Env),
                    ...(providedDeprecatedChannel
                      ? { RELEASE_CHANNEL: providedDeprecatedChannel }
                      : {}),
                  },
                })
              )?.runtimeVersion,
              platform: 'android',
            },
          ]
        : []),
    ].filter(({ runtimeVersion }) => !!runtimeVersion);
    if (!runtimeVersions.length) {
      runtimeSpinner.fail('Could not resolve runtime versions for the requested platforms');
      Log.error('Could not resolve runtime versions for the requested platforms');
      process.exit(1);
    }
    const resolvedRuntimeVersions = runtimeVersions as { runtimeVersion: string; platform: string }[];
    runtimeSpinner.succeed('✅ Runtime versions resolved');

    const latestUpdateSpinner = ora('🔎 Fetching latest updates for sourcemap release matching...')
      .start();
    let targets: {
      platform: string;
      runtimeVersion: string;
      updateId: string;
      updateUUID: string;
    }[] = [];
    try {
      targets = await Promise.all(
        resolvedRuntimeVersions.map(async ({ runtimeVersion, platform }) => {
          const updatesEndpoint = `${serverUrl}/api/branch/${branch}/runtimeVersion/${runtimeVersion}/updates`;
          const response = await fetchWithRetries(updatesEndpoint, {
            headers: { ...getAuthExpoHeaders(credentials), 'use-expo-auth': 'true' },
          });
          if (!response.ok) {
            throw new Error(`Failed to fetch updates for ${platform}: ${await response.text()}`);
          }
          const updates = (await response.json()) as DashboardUpdateItem[];
          const latestUpdate = updates.find(
            update => update.platform === platform && update.updateUUID !== 'Rollback to embedded'
          );
          if (!latestUpdate) {
            throw new Error(
              `No non-rollback update found for platform ${platform} and runtimeVersion ${runtimeVersion}`
            );
          }
          return {
            platform,
            runtimeVersion,
            updateId: latestUpdate.updateId,
            updateUUID: latestUpdate.updateUUID,
          };
        })
      );
      latestUpdateSpinner.succeed('✅ Latest update IDs resolved');
    } catch (e) {
      latestUpdateSpinner.fail('❌ Failed to resolve latest update IDs');
      Log.error(e);
      process.exit(1);
    }

    const appVersion = config.version ?? 'unknown-version';
    if (!config.version) {
      Log.warn('App version is missing in Expo config; using "unknown-version" for release name');
    }

    const sentrySpinner = ora('📤 Uploading sourcemaps to Sentry...').start();
    try {
      const { uploadedCount } = await uploadSourcemapsToSentry({
        appVersion,
        branch,
        outputDir,
        packageRunner,
        projectDir,
        targets,
        skipIfMissingAuthToken: false,
      });

      if (uploadedCount === 0) {
        throw new Error(
          `No sourcemaps were uploaded from "${outputDir}". Make sure this directory contains export artifacts.`
        );
      }

      sentrySpinner.succeed(
        `✅ Sourcemaps uploaded to Sentry (${uploadedCount} platform${uploadedCount > 1 ? 's' : ''})`
      );
    } catch (e) {
      sentrySpinner.fail('❌ Failed to upload sourcemaps to Sentry');
      Log.error(e);
      process.exit(1);
    }
  }
}
